# Generated by Django 3.1 on 2020-08-31 12:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, size=[458, 540], upload_to='team'),
        ),
    ]
