# Generated by Django 3.1 on 2020-08-31 12:30

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200831_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, size=[1600, 667], upload_to='banner'),
        ),
    ]
