# Generated by Django 3.1 on 2020-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('bio_pic', models.ImageField(upload_to='team_profile')),
                ('facebook_link', models.CharField(max_length=255)),
                ('instagram_link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Team Profile',
            },
        ),
    ]
