# Generated by Django 3.1 on 2020-10-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_teamprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Team (About Us)'},
        ),
    ]
