# Generated by Django 3.1 on 2020-08-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20200826_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('display_order',), 'verbose_name_plural': 'Packages'},
        ),
    ]
