# Generated by Django 3.1 on 2020-09-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_tourdetail_touritenary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritenary',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.tourdetail'),
        ),
    ]
