# Generated by Django 3.1 on 2020-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_auto_20200907_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
