# Generated by Django 3.1 on 2020-09-18 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='highlights',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
