# Generated by Django 3.1 on 2020-09-18 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_tourdetail_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='special_highlight',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
