# Generated by Django 3.1 on 2020-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_booknow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
