# Generated by Django 3.1 on 2020-09-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_auto_20200926_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booknow',
            options={'verbose_name_plural': 'Customer Booking'},
        ),
    ]
