# Generated by Django 3.1 on 2020-10-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_auto_20200929_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
