# Generated by Django 3.1 on 2020-10-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_tour_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
