# Generated by Django 3.1 on 2020-11-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_auto_20201101_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='price_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
