# Generated by Django 3.1 on 2020-11-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0021_auto_20201101_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='breakfast_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourdetail',
            name='cab_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourdetail',
            name='flight_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourdetail',
            name='hotel_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourdetail',
            name='sightseeing_included',
            field=models.BooleanField(default=False),
        ),
    ]
