# Generated by Django 3.1 on 2021-01-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0024_tourdetail_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourdetail',
            name='keywords',
        ),
    ]
