# Generated by Django 3.1 on 2021-01-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0025_remove_tourdetail_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetail',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
